terms_link_loc = "text=Terms and Conditions"
standard_terms_loc = "h1"
price_text_loc = "span.oe_currency_value"
plus_button_loc = "i.fa.fa-plus"
minus_button_loc = "i.fa.fa-minus"
add_cart_button_loc = "#add_to_cart_wrap"
alert_loc = "div.toast.show"
view_cart_loc = "a.btn.btn-primary[href='/shop/cart']"
cart_price_text_loc = "#cart_products .o_cart_product[data-product-id='7'] span.oe_currency_value"
quantity_input_loc = "input.js_quantity"
input_promo_loc = "[name='promo']"
button_apply_loc = ".btn-secondary"
alert_element_loc = "div.alert.alert-danger.text-start[role='alert']"
button_checkout_loc = "[name='website_sale_main_button']"
button_continue_checkout_loc = ".a-submit-disable"
note_empty_fields_loc = "h5"
select_currency_loc = "a.dropdown-toggle.btn.btn-light"
eur_option_loc = "//a[contains(@href, '/shop/change_pricelist/3')]"
price_block_loc = "div.product_price"
plus_in_cart_loc = 'a[aria-label="Add one"] i.fa-minus'
minus_in_cart_loc = 'a[aria-label="Remove one"] i.fa-minus'
